Feature/regenerate session when expired
shoplineapp/shopline-sdk-node pull request #38
Opened 2023-10-04 09:34 UTC by maryShopline

- regenerate session when sso session expired
    - store previous sso session id retrieved from current staff endpoint 
    - compare with current sso session id
    - if not match, regenerate session
- use nested property to support lower version of Node.js

2023-10-04 10:10 UTC, ken1520 approved these changes

2023-10-04 10:26 UTC, jennyc06 approved these changes

2023-10-04 10:44 UTC, terencewu-shopline requested changes

2023-10-04 10:44 UTC, terencewu-shopline commented on lib/models/DeveloperOAuth.js
> +        const currentSession = (currentStaff || {}).public_session_id_hash;
please name the variable more accurately.
* it is a session_hash (prevSession is a session, currentSession is just a string)
* it is sso session

2023-10-04 10:44 UTC, terencewu-shopline commented on lib/models/DeveloperOAuth.js
> +    const prevSession = req.session.prevSsoSessionId;
here you name it prevSsoSessionId

2023-10-05 05:13 UTC, terencewu-shopline approved these changes

2023-10-05 10:33 UTC, merged